### ISSUE TITLE
Sequel 5.0 deprecation warning

### ISSUE THREAD

**Issue by csuhta** [jeremyevans/simple_orm_benchmark#4]
Got a lot of these warnings today while running this benchmark inside a Heroku app:

```
SEQUEL DEPRECATION WARNING: Calling a dataset filtering method with a plain string is deprecated and will be removed in Sequel 5.  Use Sequel.lit("people.id = people.id") to create a literal string and pass that to the dataset filtering method, or use the auto_literal_strings extension.
/app/vendor/bundle/ruby/2.4.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1315:in `filter_expr'
/app/vendor/bundle/ruby/2.4.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1249:in `add_filter'
/app/vendor/bundle/ruby/2.4.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1034:in `where'
/app/vendor/bundle/ruby/2.4.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:218:in `filter'
/app/vendor/bundle/ruby/2.4.0/gems/sequel-4.46.0/lib/sequel/model/plugins.rb:33:in `filter'
/app/models/sequel.rb:120:in `eager_graph_party_people'
simple_orm_benchmark.rb:110:in `block (2 levels) in <main>'
simple_orm_benchmark.rb:110:in `times'
simple_orm_benchmark.rb:110:in `block in <main>'
simple_orm_benchmark.rb:207:in `instance_eval'
```

The command was:

```
$ ruby simple_orm_benchmark.rb -a -l 6
```

**Comment by jeremyevans** [comment]
Thanks for the heads up. simple_orm_benchmark will probably need to be updated for that.  I'll try to get to it today or tomorrow.
